### PR TITLE
Chore/use exth crypto#35

### LINKED ISSUE #35: Use cryptographic methods only from exth_crypto project

### PR DESCRIPTION
**Pull request by vyorkin**
closes #35

### CODE REVIEW

**Comment by ayrat555** [comment]
Something is wrong with commits. You already merged some of them in your previous PR

**Comment by vyorkin** [comment]
Nvm, I've just rebased, check it out

**Comment by ayrat555** [comment]
it looks much better

**Comment by vyorkin** [comment]
I've shut the notebook while was in the subway so haven't pulled the latest commits

**Comment by vyorkin** [comment]
ok, merging

**Pull request merged**
